name: juliatalk
description: Private Flutter chat client for JuliaTalk.
publish_to: none
version: 1.0.0+2

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.0
  flutter_secure_storage: 10.3.1
  html: 0.15.6
  http: 1.6.0
  image_picker: 1.1.2
  just_audio: ^0.10.6
  path_provider: ^2.1.6
  photo_manager: 3.9.0
  record: ^7.1.1
  url_launcher: 6.3.2
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
